language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-support
  licenses:
    - android-sdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "sources;android-27"
  - yes | sdkmanager "docs"

after_success:
  - ./gradlew javadocRelease

deploy:
  # Fix broken deployment due to
  # https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: kyrie/build/docs/javadoc/release
  on:
    branch: master
